<?php
/**
 * Created by PhpStorm.
 * User: josej_000
 * Date: 27/07/2015
 * Time: 21:47
 */

namespace project\Services;


use Prettus\Validator\Exceptions\ValidatorException;
use project\Repositories\ProjectsRepository;
use Illuminate\Http\Exception;
use project\Validators\ProjectsValidator;

class ProjectsService
{
    /**
     * @var ProjectsRepository
     */
    protected $repository;
    /**
     * @var ProjectsValidator
     */
    protected $validator;

    public function __construct(ProjectsRepository $repository, ProjectsValidator $validator)
    {
        $this->repository = $repository;
        $this->validator = $validator;
    }

    public function create(array $data)
    {
        try {
            $this->validator->with($data)->passesOrFail();
            return $this->repository->create($data);
        } catch(ValidatorException $e) {
            return [
            'error' => true,
            'message' => $e->getMessageBag()
            ];
        };

    }

    public function update(array $data, $id)
    {
        try {
            $this->validator->with($data)->passesOrFail();
            return $this->repository->update($data, $id);
        } catch(ValidatorException $e) {
            return [
                'error' => true,
                'message' => $e->getMessageBag()
            ];
        };
    }
}